name: Erlang CI

on:
  push:
    branches: [ master update_deps ]
  pull_request:
    branches: [ master update_deps ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:23.0

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit, ct
